# Configuration file for automatic testing at travis-ci.org

language: python

sudo: false

python:
#  - "2.7"
#  - "3.3"
#  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - python-dev
    - pkg-config
    - libfreetype6-dev
    - libpng-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - libatlas-base-dev
    - libx11-xcb1
    - xvfb

before_install:
    - pip install -U pip
    - pip install -U -r requirements.txt

install:
    - python setup.py install

script:
    - for x in `find / -type f -name "libqxcb.so"` ; do echo "File " $x; ldd $x; echo "\r\n"; done
    - xvfb-run python setup.py test
